### PR TITLE
Add Git wrapper

### LINKED ISSUE #1: Implement a `VersionControlSystems::Git` class
It needs to implement:

* `Git.default_branch` - What's the name of the default branch of the current repository? Probably 'main' or 'master'.
* `Git.comparison_base(sha:, comparison_branch:)` - What's the nearest common ancestor of the supplied sha and branch? This should just be `git merge-base BRANCHNAME SHA`.

### PR DESCRIPTION
**Pull request by cdimartino**
# Overview

Add a `Git` helper class, delegating to the `ruby-git` gem.

resolves https://github.com/nevinera/quiet_quality/issues/1

Supports:

- `default_branch(remote:)`
- `comparison_base(sha:, comparison_branch:)`

# Demo

```ruby
> irb
>> require "quiet_quality"
=> true
>> git = QuietQuality::VersionControlSystemsGit.new("/Users/chris/Source/quiet_quality")
=>
#<QuietQuality::Git:0x000000010801eab0
...
>> git.default_branch
=> "main"
>> git.comparison_base(sha: "head", comparison_branch: "main")
=>
[#<Git::Object::Commit:0x0000000107bc51f8
  @author=nil,
  @base=
   #<Git::Base:0x0000000108138720
    @index=#<Git::Index:0x000000010801dca0 @path="/Users/chris/Source/quiet_quality/.git/index">,
    @lib=
     #<Git::Lib:0x0000000107c81c90
      @git_dir="/Users/chris/Source/quiet_quality/.git",
      @git_index_file="/Users/chris/Source/quiet_quality/.git/index",
      @git_system_env_variables={"GIT_DIR"=>nil, "GIT_WORK_TREE"=>nil, "GIT_INDEX_FILE"=>nil, "GIT_SSH"=>nil},
      @git_work_dir="/Users/chris/Source/quiet_quality",
      @logger=
       #<Logger:0x000000010801e240
        @default_formatter=#<Logger::Formatter:0x000000010801e0d8 @datetime_format=nil>,
        @formatter=nil,
        @level=0,
        @logdev=nil,
        @progname=nil>,
      @path=nil>,
    @logger=
     #<Logger:0x000000010801e240
      @default_formatter=#<Logger::Formatter:0x000000010801e0d8 @datetime_format=nil>,
      @formatter=nil,
      @level=0,
      @logdev=nil,
      @progname=nil>,
    @repository=#<Git::Repository:0x000000010801dd68 @path="/Users/chris/Source/quiet_quality/.git">,
    @working_directory=#<Git::WorkingDirectory:0x000000010801dea8 @path="/Users/chris/Source/quiet_quality">>,
  @committer=nil,
  @contents=nil,
  @message=nil,
  @objectish="ad70c07809b1c30ceecd552449d5223c2c97f420",
  @parents=nil,
  @sha=nil,
  @size=nil,
  @tree=nil,
  @trees=nil>]
>>
```

### CODE REVIEW

**Review by nevinera — APPROVED** [review]
Should we include the abstract wrapper here, or make that a separate slice? I assume the actual cli class will take a --vcs flag, that controls which subsystem to use, and will pass that flag into some kind of dispatcher? Do we want to go OO there, or use a real dispatcher pattern? I suspect "merge_base" is git-specific for example, but the concept we're calling it for isn't (`comparison_target` maybe?)

**Comment by nevinera** [comment]
Or perhaps we shouldn't worry about it, until someone actually wants to use this with another VCS:-)

**Comment by cdimartino** [comment]
Might be best to hold off until we need it. All the cool kids use `git` ;)

**Comment by cdimartino** [comment]
I don't like how mocked the specs are - I caught a bug or two in `irb` while playing with it. Going to rewrite them to actually exercise the repo, since we _are_ a repo...

**Comment by cdimartino** [comment]
> I don't like how mocked the specs are - I caught a bug or two in `irb` while playing with it. Going to rewrite them to actually exercise the repo, since we _are_ a repo...

That worked locally, but blew up in ci/cd. Reverting to the mocks for now.

**Comment by nevinera** [comment]
> > I don't like how mocked the specs are - I caught a bug or two in `irb` while playing with it. Going to rewrite them to actually exercise the repo, since we _are_ a repo...
> 
> That worked locally, but blew up in ci/cd. Reverting to the mocks for now.

It's a shallow clone in CI :-)

If we wanted to actually exercise it, we'd probably want to zip up a separate simple git repository into an artifact fixture. But that does add some complexity to the specs..

**Pull request merged**
